#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (c) 2020, Wenbin Fei, Email: wenbinfei@gmail.com
# All rights reserved.

"""
Have fun with images.
"""

from PIL import Image
import os
import logging.config
import time
import traceback

# Create logger
logging.config.fileConfig(fname='logging.ini')
logger = logging.getLogger(__name__)

def crop_journal_image(path):
    """
    crop the images generated by PPT acrrosing one column or two columns in the journal

    :type path: string
    :param path: the directory of the iamges, call and replace the same figure 
    """

def generate_long_image(output_path):
    """
    generate long image by combing individual images

    :type output_path: string
    :param input_file: the directory of the iamges to be saved 
    """
    try:
        picture_path = output_path[:output_path.rfind('.')]
        last_dir = os.path.dirname(picture_path)  # parent directory

        # achevie individual images
        ims = [Image.open(os.path.join(picture_path, fn)) for fn in os.listdir(picture_path)]
        width, height = ims[0].size   
        long_canvas = Image.new(ims[1].mode, (width, height * len(ims))) #create n photos with the same width
    except: 
        logger.error(traceback.format_exc())
    else:
        # merge figures
        for i, image in enumerate(ims):
                long_canvas.paste(image, box=(0, i * height))

        long_canvas.save(os.path.join(last_dir, 'long-image.tif'))  # save as long figure
        logger.info(f"[generate_long_image completed]")

    